import { Link } from "react-router-dom";
import SeoHead from "../../components/SeoHead";
import FAQ from "../../components/FAQ";

const s = {
  page: { maxWidth: 800, margin: "0 auto" },
  backLink: { color: "var(--text-muted)", fontSize: 13, textDecoration: "none", display: "inline-block", marginBottom: 24 },
  title: { fontFamily: "var(--font-display)", fontSize: 36, marginBottom: 8, lineHeight: 1.2 },
  meta: { color: "var(--text-muted)", fontSize: 13, marginBottom: 32 },
  h2: { fontFamily: "var(--font-display)", fontSize: 24, marginTop: 40, marginBottom: 12, color: "var(--text)" },
  h3: { fontSize: 18, fontWeight: 600, marginTop: 28, marginBottom: 8, color: "var(--text)" },
  p: { fontSize: 15, lineHeight: 1.8, color: "var(--text-secondary)", marginBottom: 16 },
  table: { width: "100%", borderCollapse: "collapse", marginBottom: 24, fontSize: 14 },
  th: { textAlign: "left", padding: "10px 8px", borderBottom: "2px solid var(--border)", color: "var(--text-secondary)", fontWeight: 600, background: "var(--surface)" },
  td: { padding: "10px 8px", borderBottom: "1px solid var(--border)" },
  link: { color: "var(--gold)", fontWeight: 500, textDecoration: "none" },
  callout: { padding: 20, background: "var(--gold-bg)", border: "1px solid rgba(240,180,41,0.2)", borderRadius: "var(--radius-lg)", marginBottom: 24, fontSize: 14, lineHeight: 1.7, color: "var(--text-secondary)" },
  calloutTitle: { fontWeight: 600, color: "var(--gold)", marginBottom: 8 },
  ul: { paddingLeft: 20, marginBottom: 16, fontSize: 15, lineHeight: 1.8, color: "var(--text-secondary)" },
  ol: { paddingLeft: 20, marginBottom: 16, fontSize: 15, lineHeight: 1.8, color: "var(--text-secondary)" },
};

const TEMPLATES = [
  { name: "Rent Receipt", category: "Rental", useCase: "HRA tax exemption claims", slug: "rent-receipt-generator" },
  { name: "Rental Agreement", category: "Rental", useCase: "11-month lease between landlord & tenant", slug: "rental-agreement-generator" },
  { name: "Salary Slip", category: "HR", useCase: "Monthly salary breakdown for employees", slug: "salary-slip-generator" },
  { name: "Experience Letter", category: "HR", useCase: "Employment verification for past employees", slug: "experience-letter-generator" },
  { name: "Relieving Letter", category: "HR", useCase: "Formal end-of-employment confirmation", slug: "relieving-letter-generator" },
  { name: "Offer Letter", category: "HR", useCase: "Job offers with compensation details", slug: "offer-letter-generator" },
  { name: "Appointment Letter", category: "HR", useCase: "Formal employment appointment", slug: "appointment-letter-generator" },
  { name: "Resignation Letter", category: "HR", useCase: "Professional resignation from employment", slug: "resignation-letter-generator" },
  { name: "Leave Application", category: "HR", useCase: "Casual, sick, earned, maternity leave", slug: "leave-application-generator" },
  { name: "Salary Certificate", category: "HR", useCase: "Income verification for loans, visas", slug: "salary-certificate-generator" },
  { name: "Invoice", category: "Business", useCase: "GST-compliant invoices with tax", slug: "invoice-generator" },
  { name: "Partnership Deed", category: "Business", useCase: "Partnership terms, capital, profit sharing", slug: "partnership-deed-generator" },
  { name: "NOC Letter", category: "Legal", useCase: "No Objection Certificate for various purposes", slug: "noc-letter-generator" },
  { name: "Power of Attorney", category: "Legal", useCase: "Authorize someone to act on your behalf", slug: "power-of-attorney-generator" },
  { name: "Affidavit", category: "Legal", useCase: "Sworn statement for legal/official purposes", slug: "affidavit-generator" },
  { name: "Authorization Letter", category: "Legal", useCase: "Authorize third-party actions", slug: "authorization-letter-generator" },
  { name: "Bonafide Certificate", category: "Legal", useCase: "Verify student/employee authenticity", slug: "bonafide-certificate-generator" },
  { name: "Warning Letter", category: "HR", useCase: "Formal employee warning for misconduct/performance", slug: "employee-warning-letter-generator" },
  { name: "Internship Certificate", category: "HR", useCase: "Internship completion certificate with rating", slug: "internship-certificate-generator" },
];

const FAQS = [
  { q: "Are these document templates legally valid in India?", a: "The templates generated by DoAide Docs are properly formatted and contain all standard clauses used in Indian legal practice. However, some documents (like affidavits, power of attorney, and partnership deeds) need to be printed on appropriate stamp paper and notarized to be legally enforceable. The template gives you the correct format — notarization and stamp duty give it legal force." },
  { q: "Do I need to notarize every document?", a: "No, not all documents need notarization. Rent receipts, salary slips, experience letters, and invoices are valid without notarization. Documents that typically need notarization include affidavits, power of attorney, partnership deeds, and rental agreements (if registered). NOC letters may or may not need notarization depending on the purpose." },
  { q: "Is my data safe when generating documents?", a: "Yes, 100%. All documents are generated entirely in your browser using JavaScript. No data is sent to any server — everything happens on your device. You can verify this by disconnecting from the internet and the generator will still work. We do not store, collect, or transmit any information you enter." },
  { q: "Can I edit the document after downloading the PDF?", a: "PDF files are not easily editable. We recommend making all changes in the online form before downloading. If you need to make changes later, simply revisit the generator, re-enter your details (or modify them), and download a new PDF. For advanced editing, you can import the PDF into tools like Adobe Acrobat or Canva." },
  { q: "Which documents need to be printed on stamp paper?", a: "Documents that typically require stamp paper in India include: Affidavits (₹10-₹100 depending on state), Rental Agreements (varies by state — ₹100-₹500), Partnership Deeds (₹500-₹1,000 depending on capital and state), and Power of Attorney (₹100-₹500). Stamp duty rates vary by state. Rent receipts, salary slips, and letters do not need stamp paper." },
];

export default function FreeLegalDocTemplatesIndia() {
  return (
    <div style={s.page}>
      <SeoHead
        title="Free Legal Document Templates India — Download PDF Instantly | DoAide Docs"
        description="Top 17 free legal document templates for India — rent agreements, affidavits, power of attorney, NOC letters, invoices, and more. Generate and download as PDF with no login required."
        slug="blog/free-legal-document-templates-india"
        faqs={FAQS}
      />
      <Link to="/blog" style={s.backLink}>← Back to Blog</Link>

      <h1 style={s.title}>Free Legal Document Templates India — Download PDF Instantly</h1>
      <p style={s.meta}>Updated October 2026 · 10 min read</p>

      <p style={s.p}>
        Whether you are a small business owner drafting an invoice, an employee needing a resignation letter, a landlord
        preparing a rent agreement, or someone who needs an affidavit notarized — you should not have to pay a lawyer
        for a standard template. DoAide Docs offers 19 free document generators that create properly formatted, downloadable
        PDFs in seconds — with no login, no signup, and no data leaving your browser.
      </p>

      <div style={s.callout}>
        <div style={s.calloutTitle}>All Templates Are Free</div>
        Every generator on DoAide Docs is 100% free with no hidden charges. Your data never leaves your browser —
        all processing happens locally on your device.
      </div>

      <h2 style={s.h2}>Complete List of Templates</h2>
      <div style={{ overflowX: "auto" }}>
        <table style={s.table}>
          <thead>
            <tr>
              <th style={s.th}>Template</th>
              <th style={s.th}>Category</th>
              <th style={s.th}>Use Case</th>
            </tr>
          </thead>
          <tbody>
            {TEMPLATES.map((t) => (
              <tr key={t.slug}>
                <td style={s.td}><Link to={`/${t.slug}`} style={s.link}>{t.name}</Link></td>
                <td style={s.td}>{t.category}</td>
                <td style={{ ...s.td, fontSize: 13 }}>{t.useCase}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <h2 style={s.h2}>Rental Documents</h2>
      <p style={s.p}>
        Rental documents are among the most commonly needed templates in India. Whether you are a tenant claiming HRA
        exemption or a landlord formalizing a tenancy, our generators cover both needs:
      </p>
      <ul style={s.ul}>
        <li><Link to="/rent-receipt-generator" style={s.link}>Rent Receipt Generator</Link> — Generate monthly rent receipts for HRA tax exemption. Includes landlord name, tenant details, amount, and period. Essential for salaried individuals claiming HRA under Section 10(13A).</li>
        <li><Link to="/rental-agreement-generator" style={s.link}>Rental Agreement Generator</Link> — Create 11-month rental agreements with all standard clauses including rent amount, security deposit, maintenance, lock-in period, and termination terms.</li>
      </ul>

      <h2 style={s.h2}>Employment & HR Documents</h2>
      <p style={s.p}>
        HR professionals, business owners, and employees frequently need these documents. All templates follow
        standard Indian corporate formatting:
      </p>
      <ul style={s.ul}>
        <li><Link to="/salary-slip-generator" style={s.link}>Salary Slip</Link> — Full breakdown with basic, HRA, DA, conveyance, PF, ESI, and TDS deductions</li>
        <li><Link to="/offer-letter-generator" style={s.link}>Offer Letter</Link> — Job offer with CTC, designation, joining date, and terms</li>
        <li><Link to="/appointment-letter-generator" style={s.link}>Appointment Letter</Link> — Formal appointment confirmation for new joiners</li>
        <li><Link to="/experience-letter-generator" style={s.link}>Experience Letter</Link> — Employment verification with designation and period</li>
        <li><Link to="/relieving-letter-generator" style={s.link}>Relieving Letter</Link> — Confirmation of end of employment</li>
        <li><Link to="/resignation-letter-generator" style={s.link}>Resignation Letter</Link> — Professional resignation with notice period and handover</li>
        <li><Link to="/leave-application-generator" style={s.link}>Leave Application</Link> — Casual, sick, earned, or maternity leave requests</li>
        <li><Link to="/salary-certificate-generator" style={s.link}>Salary Certificate</Link> — Income verification for bank loans, visas, and verification</li>
        <li><Link to="/employee-warning-letter-generator" style={s.link}>Employee Warning Letter</Link> — Formal warnings for misconduct, poor performance, or attendance issues</li>
        <li><Link to="/internship-certificate-generator" style={s.link}>Internship Certificate</Link> — Completion certificates with project details and performance rating</li>
      </ul>

      <h2 style={s.h2}>Legal Documents</h2>
      <p style={s.p}>
        Legal documents typically need additional steps like notarization or stamp paper. Our generators give you the
        correct format — print on stamp paper and get it notarized at any notary office (₹50-₹200).
      </p>
      <ul style={s.ul}>
        <li><Link to="/affidavit-generator" style={s.link}>Affidavit</Link> — Sworn statements for identity proof, address proof, name change, lost documents, and more</li>
        <li><Link to="/power-of-attorney-generator" style={s.link}>Power of Attorney</Link> — General or special PoA to authorize someone to act on your behalf</li>
        <li><Link to="/noc-letter-generator" style={s.link}>NOC Letter</Link> — No Objection Certificates for vehicle transfer, society, employment, and more</li>
        <li><Link to="/authorization-letter-generator" style={s.link}>Authorization Letter</Link> — Authorize third parties for bank transactions, document collection, etc.</li>
        <li><Link to="/bonafide-certificate-generator" style={s.link}>Bonafide Certificate</Link> — Verify student or employee authenticity for official purposes</li>
      </ul>

      <h2 style={s.h2}>Business Documents</h2>
      <ul style={s.ul}>
        <li><Link to="/invoice-generator" style={s.link}>Invoice Generator</Link> — GST-compliant invoices with CGST, SGST, IGST calculations, line items, and totals</li>
        <li><Link to="/partnership-deed-generator" style={s.link}>Partnership Deed</Link> — Partnership agreements with capital contribution, profit sharing, management, and dissolution terms</li>
      </ul>

      <h2 style={s.h2}>Tips for Using Document Templates</h2>
      <ol style={s.ol}>
        <li><strong>Fill all required fields</strong> — Missing information can make a document invalid or cause delays at government offices.</li>
        <li><strong>Check stamp paper requirements</strong> — Affidavits, partnership deeds, and rental agreements typically need stamp paper. Check your state's rates.</li>
        <li><strong>Get notarization when needed</strong> — Visit any Notary Public with the printed document and valid ID proof. Cost is usually ₹50-₹200.</li>
        <li><strong>Keep copies</strong> — Always keep a digital copy (PDF) and a physical copy of important documents.</li>
        <li><strong>Verify details before downloading</strong> — Use the live preview to check all information. Re-download if you need changes.</li>
      </ol>

      <h2 style={s.h2}>Why DoAide Docs is Free and Private</h2>
      <p style={s.p}>
        Unlike other document generators that charge fees or require sign-ups, DoAide Docs is completely free. Every
        document is generated in your browser using JavaScript — no data is ever sent to a server. You can verify this
        by disconnecting from the internet: the generators will still work perfectly. We believe everyone should have
        access to properly formatted legal and professional documents without barriers.
      </p>

      <FAQ items={FAQS} />

      <div style={{ marginTop: 40, padding: 20, background: "var(--surface)", borderRadius: "var(--radius-lg)" }}>
        <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 12, color: "var(--gold)" }}>Most Popular Templates</h3>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
          {[
            { to: "/rent-receipt-generator", label: "Rent Receipt" },
            { to: "/rental-agreement-generator", label: "Rental Agreement" },
            { to: "/salary-slip-generator", label: "Salary Slip" },
            { to: "/invoice-generator", label: "Invoice" },
            { to: "/resignation-letter-generator", label: "Resignation Letter" },
            { to: "/affidavit-generator", label: "Affidavit" },
            { to: "/partnership-deed-generator", label: "Partnership Deed" },
          ].map((t) => (
            <Link key={t.to} to={t.to} style={{ padding: "8px 16px", background: "var(--gold-bg)", border: "1px solid rgba(240,180,41,0.2)", borderRadius: 20, fontSize: 13, color: "var(--gold)", textDecoration: "none", fontWeight: 500 }}>
              {t.label}
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
